// Command estimationd serves the estimation service over HTTP.
//
// Usage:
//
//	estimationd --ai-provider=mock --addr=:8080
//	estimationd --ai-provider=anthropic --addr=:8080
//
// With --ai-provider=mock the deterministic QA priming affordance
// (POST /qa/ai/next-wbs) is enabled and no network LLM is used. With
// --ai-provider=anthropic the WBS is generated by Claude via the Anthropic API
// (credentials resolved from ANTHROPIC_API_KEY or an authenticated profile).
package main

import (
	"flag"
	"log"
	"net/http"

	"estimation/internal/aiprovider"
	"estimation/internal/httpapi"
	"estimation/internal/wbs"
	"estimation/internal/webui"
)

func main() {
	addr := flag.String("addr", ":8080", "address to listen on")
	aiProvider := flag.String("ai-provider", "", "AI provider: \"mock\" for deterministic QA mode, \"anthropic\" for Claude")
	model := flag.String("model", "", "Claude model id (anthropic provider only; empty uses the default)")
	flag.Parse()

	srv, err := buildServer(*aiProvider, *model)
	if err != nil {
		log.Fatalf("estimationd: %v", err)
	}

	log.Printf("estimationd listening on %s (ai-provider=%q)", *addr, *aiProvider)
	if err := http.ListenAndServe(*addr, srv); err != nil {
		log.Fatalf("estimationd: %v", err)
	}
}

func buildServer(provider, model string) (http.Handler, error) {
	svc, mock := serviceForProvider(provider, model)
	// The service is shared: the two-stage UI at / and the JSON API operate on
	// the same in-memory estimate, and the QA priming affordance is enabled only
	// in mock mode on both surfaces.
	ui := webui.NewHandlerWithService(svc, mock)
	api := httpapi.NewServerWithService(svc, mock)
	return compose(ui, api), nil
}

// serviceForProvider builds the WBS service for the named AI provider, reporting
// whether the deterministic QA priming affordance is enabled (mock only).
func serviceForProvider(provider, model string) (svc *wbs.Service, mock bool) {
	switch provider {
	case "anthropic":
		// The Anthropic provider generates WBSs, flags their risks, and produces
		// their 3-point estimates.
		claude := aiprovider.New(model)
		return wbs.NewServiceWithProviders(claude, claude, claude), false
	case "mock":
		return wbs.NewService(), true
	default:
		// No provider configured: run without the QA priming affordance and
		// with the default (empty) deterministic provider.
		return wbs.NewService(), false
	}
}

// compose mounts the two-stage UI as the site root and routes the JSON API's
// paths to it. The UI owns / (and /proposal, /ui/*); the API owns /wbs and
// /qa/ai/*.
func compose(ui, api http.Handler) http.Handler {
	mux := http.NewServeMux()
	mux.Handle("/", ui)
	mux.Handle("/wbs", api)
	mux.Handle("/wbs/", api)
	mux.Handle("/qa/", api)
	return mux
}
