// Command estimationd serves the estimation service over HTTP.
//
// Usage:
//
//	estimationd --ai-provider=mock --addr=:8080
//	estimationd --ai-provider=anthropic --addr=:8080
//
// With --ai-provider=mock the deterministic QA priming affordance
// (POST /qa/ai/next-wbs) is enabled and no network LLM is used. With
// --ai-provider=anthropic the WBS is generated by Claude via the Anthropic API
// (credentials resolved from ANTHROPIC_API_KEY or an authenticated profile).
package main

import (
	"flag"
	"log"
	"net/http"

	"estimation/internal/aiprovider"
	"estimation/internal/httpapi"
	"estimation/internal/wbs"
)

func main() {
	addr := flag.String("addr", ":8080", "address to listen on")
	aiProvider := flag.String("ai-provider", "", "AI provider: \"mock\" for deterministic QA mode, \"anthropic\" for Claude")
	model := flag.String("model", "", "Claude model id (anthropic provider only; empty uses the default)")
	flag.Parse()

	srv, err := buildServer(*aiProvider, *model)
	if err != nil {
		log.Fatalf("estimationd: %v", err)
	}

	log.Printf("estimationd listening on %s (ai-provider=%q)", *addr, *aiProvider)
	if err := http.ListenAndServe(*addr, srv); err != nil {
		log.Fatalf("estimationd: %v", err)
	}
}

func buildServer(provider, model string) (http.Handler, error) {
	switch provider {
	case "anthropic":
		claude := aiprovider.New(model)
		// The Anthropic provider generates WBSs, flags their risks, and produces
		// their 3-point estimates.
		svc := wbs.NewServiceWithProviders(claude, claude, claude)
		return httpapi.NewServerWithService(svc, false), nil
	case "mock":
		return httpapi.NewServer(true), nil
	default:
		// No provider configured: run without the QA priming affordance and
		// with the default (empty) deterministic provider.
		return httpapi.NewServer(false), nil
	}
}
