// Command acceptance-entrypoint-generator turns parser JSON IR into a Go
// acceptance entry point. Each generated file embeds the JSON IR and registers
// it with the acceptance runtime. It writes thin entry points only; step
// handlers and the runtime are hand-written elsewhere.
//
// Usage:
//
//	acceptance-entrypoint-generator <json-ir> <generated-test-output-dir>
//
// The optional environment variable ACCEPTANCE_FEATURE_PATH records the source
// feature path in the generated metadata.
package main

import (
	"crypto/sha256"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

func main() {
	os.Exit(run(os.Args[1:]))
}

func run(args []string) int {
	if len(args) != 2 {
		fmt.Fprintln(os.Stderr, "usage: acceptance-entrypoint-generator <json-ir> <generated-test-output-dir>")
		return 2
	}
	irPath, outDir := args[0], args[1]

	irBytes, err := os.ReadFile(irPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "read IR: %v\n", err)
		return 1
	}
	if !json.Valid(irBytes) {
		fmt.Fprintf(os.Stderr, "IR %s is not valid JSON\n", irPath)
		return 1
	}

	featurePath := os.Getenv("ACCEPTANCE_FEATURE_PATH")
	if featurePath == "" {
		featurePath = irPath
	}
	slug := identifier(baseName(irPath))

	genName := slug + "_gen.go"
	genPath := filepath.Join(outDir, genName)
	genContent := generatedSource(string(irBytes))

	if err := os.MkdirAll(outDir, 0o755); err != nil {
		fmt.Fprintf(os.Stderr, "create output dir: %v\n", err)
		return 1
	}
	if err := os.WriteFile(genPath, []byte(genContent), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "write generated entry point: %v\n", err)
		return 1
	}

	if err := writeMetadata(outDir, featurePath, irPath, genPath, genContent); err != nil {
		fmt.Fprintf(os.Stderr, "write metadata: %v\n", err)
		return 1
	}
	return 0
}

func generatedSource(irJSON string) string {
	var b strings.Builder
	b.WriteString("// Code generated by acceptance-entrypoint-generator. DO NOT EDIT.\n")
	b.WriteString("package main\n\n")
	b.WriteString("import \"estimation/acceptance/runtime\"\n\n")
	b.WriteString("func init() {\n")
	b.WriteString("\truntime.MustRegister(`")
	b.WriteString(irJSON)
	b.WriteString("`)\n")
	b.WriteString("}\n")
	return b.String()
}

func writeMetadata(outDir, featurePath, irPath, genPath, genContent string) error {
	metaDir := filepath.Join(outDir, "metadata")
	if err := os.MkdirAll(metaDir, 0o755); err != nil {
		return err
	}
	sum := sha256.Sum256([]byte(genContent))
	meta := map[string]any{
		"schema_version":      1,
		"feature_path":        featurePath,
		"ir_path":             irPath,
		"implementation_hash": fmt.Sprintf("sha256:%x", sum),
		"hash_scope":          "generated_files",
		"generated_files":     []string{filepath.ToSlash(genPath)},
	}
	data, err := json.MarshalIndent(meta, "", "  ")
	if err != nil {
		return err
	}
	metaPath := filepath.Join(metaDir, metadataName(featurePath))
	return os.WriteFile(metaPath, append(data, '\n'), 0o644)
}

func baseName(path string) string {
	base := filepath.Base(path)
	return strings.TrimSuffix(base, filepath.Ext(base))
}

var nonAlnum = regexp.MustCompile(`[^a-z0-9]+`)

// metadataName maps a feature path to its metadata filename: lowercase, every
// run of non-alphanumeric characters replaced by one hyphen, trimmed, with
// ".json" appended.
func metadataName(featurePath string) string {
	slug := nonAlnum.ReplaceAllString(strings.ToLower(featurePath), "-")
	slug = strings.Trim(slug, "-")
	return slug + ".json"
}

var nonIdent = regexp.MustCompile(`[^a-z0-9]+`)

// identifier turns a base name into a safe file-name stem.
func identifier(base string) string {
	id := nonIdent.ReplaceAllString(strings.ToLower(base), "_")
	return strings.Trim(id, "_")
}
