package generator

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

const sampleIR = `{"name":"WBS Approval","background":[],"scenarios":[]}`

func noEnv(string) string { return "" }

func TestRunGeneratesEntryPointAndMetadata(t *testing.T) {
	dir := t.TempDir()
	irPath := filepath.Join(dir, "wbs_approval.json")
	if err := os.WriteFile(irPath, []byte(sampleIR), 0o644); err != nil {
		t.Fatalf("write IR: %v", err)
	}
	outDir := filepath.Join(dir, "generated")

	var stderr strings.Builder
	if code := Run([]string{irPath, outDir}, noEnv, &stderr); code != 0 {
		t.Fatalf("Run code = %d (stderr %q), want 0", code, stderr.String())
	}

	gen, err := os.ReadFile(filepath.Join(outDir, "wbs_approval_gen.go"))
	if err != nil {
		t.Fatalf("read generated file: %v", err)
	}
	genStr := string(gen)
	if !strings.Contains(genStr, "DO NOT EDIT") ||
		!strings.Contains(genStr, "runtime.MustRegister(`"+sampleIR+"`)") {
		t.Fatalf("generated source unexpected:\n%s", genStr)
	}

	meta := readOnlyMetadata(t, outDir)
	if meta["feature_path"] != irPath {
		t.Fatalf("feature_path = %v, want %s (defaults to IR path)", meta["feature_path"], irPath)
	}
	if !strings.HasPrefix(meta["implementation_hash"].(string), "sha256:") {
		t.Fatalf("implementation_hash = %v, want sha256 prefix", meta["implementation_hash"])
	}
}

func TestRunRecordsFeaturePathFromEnv(t *testing.T) {
	dir := t.TempDir()
	irPath := filepath.Join(dir, "wbs_editing.json")
	if err := os.WriteFile(irPath, []byte(sampleIR), 0o644); err != nil {
		t.Fatalf("write IR: %v", err)
	}
	outDir := filepath.Join(dir, "generated")

	getenv := func(k string) string {
		if k == "ACCEPTANCE_FEATURE_PATH" {
			return "features/wbs_editing.feature"
		}
		return ""
	}
	var stderr strings.Builder
	if code := Run([]string{irPath, outDir}, getenv, &stderr); code != 0 {
		t.Fatalf("Run code = %d (stderr %q), want 0", code, stderr.String())
	}

	// The env-supplied feature path drives the metadata filename slug.
	meta := readMetadata(t, outDir, "features-wbs-editing-feature.json")
	if meta["feature_path"] != "features/wbs_editing.feature" {
		t.Fatalf("feature_path = %v, want the env value", meta["feature_path"])
	}
}

func TestRunRejectsWrongArgCount(t *testing.T) {
	var stderr strings.Builder
	if code := Run([]string{"only-one"}, noEnv, &stderr); code != 2 {
		t.Fatalf("code = %d, want 2 for usage error", code)
	}
	if !strings.Contains(stderr.String(), "usage:") {
		t.Fatalf("stderr = %q, want usage message", stderr.String())
	}
}

func TestRunReportsUnreadableIR(t *testing.T) {
	var stderr strings.Builder
	missing := filepath.Join(t.TempDir(), "absent.json")
	if code := Run([]string{missing, t.TempDir()}, noEnv, &stderr); code != 1 {
		t.Fatalf("code = %d, want 1 for read failure", code)
	}
	if !strings.Contains(stderr.String(), "read IR:") {
		t.Fatalf("stderr = %q, want read IR diagnostic", stderr.String())
	}
}

func TestRunReportsInvalidJSON(t *testing.T) {
	dir := t.TempDir()
	irPath := filepath.Join(dir, "bad.json")
	if err := os.WriteFile(irPath, []byte("{not json"), 0o644); err != nil {
		t.Fatalf("write IR: %v", err)
	}
	var stderr strings.Builder
	if code := Run([]string{irPath, filepath.Join(dir, "out")}, noEnv, &stderr); code != 1 {
		t.Fatalf("code = %d, want 1 for invalid JSON", code)
	}
	if !strings.Contains(stderr.String(), "not valid JSON") {
		t.Fatalf("stderr = %q, want invalid JSON diagnostic", stderr.String())
	}
}

func TestGenerateRejectsInvalidJSONWithoutWriting(t *testing.T) {
	outDir := filepath.Join(t.TempDir(), "generated")
	err := Generate([]byte("{nope"), outDir, "f", "f.json")
	if err == nil || !strings.Contains(err.Error(), "not valid JSON") {
		t.Fatalf("Generate error = %v, want invalid JSON", err)
	}
	if _, statErr := os.Stat(outDir); !os.IsNotExist(statErr) {
		t.Fatalf("output dir created despite invalid IR")
	}
}

func TestGeneratedSourceIsStable(t *testing.T) {
	got := generatedSource(`{"x":1}`)
	want := "// Code generated by acceptance-entrypoint-generator. DO NOT EDIT.\n" +
		"package main\n\n" +
		"import \"estimation/acceptance/runtime\"\n\n" +
		"func init() {\n" +
		"\truntime.MustRegister(`{\"x\":1}`)\n" +
		"}\n"
	if got != want {
		t.Fatalf("generatedSource =\n%q\nwant\n%q", got, want)
	}
}

func TestBaseName(t *testing.T) {
	cases := map[string]string{
		"features/wbs_approval.feature": "wbs_approval",
		"a.json":                        "a",
		"noext":                         "noext",
	}
	for in, want := range cases {
		if got := baseName(in); got != want {
			t.Fatalf("baseName(%q) = %q, want %q", in, got, want)
		}
	}
}

func TestMetadataNameAndIdentifier(t *testing.T) {
	if got := metadataName("features/WBS Editing.feature"); got != "features-wbs-editing-feature.json" {
		t.Fatalf("metadataName = %q", got)
	}
	if got := identifier("WBS-Approval Flow"); got != "wbs_approval_flow" {
		t.Fatalf("identifier = %q", got)
	}
}

func readMetadata(t *testing.T, outDir, name string) map[string]any {
	t.Helper()
	return decodeMetadata(t, filepath.Join(outDir, "metadata", name))
}

// readOnlyMetadata reads the sole metadata file under outDir. Use it when the
// filename slug derives from an unpredictable path (e.g. a temp dir).
func readOnlyMetadata(t *testing.T, outDir string) map[string]any {
	t.Helper()
	entries, err := os.ReadDir(filepath.Join(outDir, "metadata"))
	if err != nil {
		t.Fatalf("read metadata dir: %v", err)
	}
	if len(entries) != 1 {
		t.Fatalf("got %d metadata files, want exactly 1", len(entries))
	}
	return decodeMetadata(t, filepath.Join(outDir, "metadata", entries[0].Name()))
}

func decodeMetadata(t *testing.T, path string) map[string]any {
	t.Helper()
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read metadata %s: %v", path, err)
	}
	var meta map[string]any
	if err := json.Unmarshal(data, &meta); err != nil {
		t.Fatalf("metadata is not valid JSON: %v", err)
	}
	return meta
}
