// Package generator turns parser JSON IR into a Go acceptance entry point. Each
// generated file embeds the JSON IR and registers it with the acceptance
// runtime. The generator writes thin entry points only; step handlers and the
// runtime are hand-written elsewhere.
//
// This package holds the testable behavior. The command
// (cmd/acceptance-entrypoint-generator) is a thin shell that wires it to the
// process environment.
package generator

import (
	"crypto/sha256"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

// Run is the command adapter: it parses arguments, reads the IR file, resolves
// the recorded feature path, and generates the entry point. It reports usage
// and failures to stderr and returns the process exit code (2 for a usage
// error, 1 for a generation failure, 0 on success). getenv supplies
// environment lookups so the behavior is testable without process state.
func Run(args []string, getenv func(string) string, stderr io.Writer) int {
	if len(args) != 2 {
		fmt.Fprintln(stderr, "usage: acceptance-entrypoint-generator <json-ir> <generated-test-output-dir>")
		return 2
	}
	irPath, outDir := args[0], args[1]

	irBytes, err := os.ReadFile(irPath)
	if err != nil {
		fmt.Fprintf(stderr, "read IR: %v\n", err)
		return 1
	}

	featurePath := getenv("ACCEPTANCE_FEATURE_PATH")
	if featurePath == "" {
		featurePath = irPath
	}

	if err := Generate(irBytes, outDir, featurePath, irPath); err != nil {
		fmt.Fprintf(stderr, "%v\n", err)
		return 1
	}
	return 0
}

// Generate writes the generated entry point and its metadata for one feature
// IR into outDir. featurePath and irPath are recorded in the metadata. An IR
// that is not valid JSON is rejected and nothing is written.
func Generate(irBytes []byte, outDir, featurePath, irPath string) error {
	if !json.Valid(irBytes) {
		return fmt.Errorf("IR %s is not valid JSON", irPath)
	}

	genPath := filepath.Join(outDir, identifier(baseName(irPath))+"_gen.go")
	genContent := generatedSource(string(irBytes))

	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return fmt.Errorf("create output dir: %w", err)
	}
	if err := os.WriteFile(genPath, []byte(genContent), 0o644); err != nil {
		return fmt.Errorf("write generated entry point: %w", err)
	}
	if err := writeMetadata(outDir, featurePath, irPath, genPath, genContent); err != nil {
		return fmt.Errorf("write metadata: %w", err)
	}
	return nil
}

func generatedSource(irJSON string) string {
	var b strings.Builder
	b.WriteString("// Code generated by acceptance-entrypoint-generator. DO NOT EDIT.\n")
	b.WriteString("package main\n\n")
	b.WriteString("import \"estimation/acceptance/runtime\"\n\n")
	b.WriteString("func init() {\n")
	b.WriteString("\truntime.MustRegister(`")
	b.WriteString(irJSON)
	b.WriteString("`)\n")
	b.WriteString("}\n")
	return b.String()
}

func writeMetadata(outDir, featurePath, irPath, genPath, genContent string) error {
	metaDir := filepath.Join(outDir, "metadata")
	if err := os.MkdirAll(metaDir, 0o755); err != nil {
		return err
	}
	sum := sha256.Sum256([]byte(genContent))
	meta := map[string]any{
		"schema_version":      1,
		"feature_path":        featurePath,
		"ir_path":             irPath,
		"implementation_hash": fmt.Sprintf("sha256:%x", sum),
		"hash_scope":          "generated_files",
		"generated_files":     []string{filepath.ToSlash(genPath)},
	}
	data, err := json.MarshalIndent(meta, "", "  ")
	if err != nil {
		return err
	}
	metaPath := filepath.Join(metaDir, metadataName(featurePath))
	return os.WriteFile(metaPath, append(data, '\n'), 0o644)
}

func baseName(path string) string {
	base := filepath.Base(path)
	return strings.TrimSuffix(base, filepath.Ext(base))
}

// nonAlnum matches every run of characters that is not a lowercase letter or
// digit. Both slug builders below collapse such runs to a single separator.
var nonAlnum = regexp.MustCompile(`[^a-z0-9]+`)

// metadataName maps a feature path to its metadata filename: lowercase, every
// run of non-alphanumeric characters replaced by one hyphen, trimmed, with
// ".json" appended.
func metadataName(featurePath string) string {
	slug := nonAlnum.ReplaceAllString(strings.ToLower(featurePath), "-")
	slug = strings.Trim(slug, "-")
	return slug + ".json"
}

// identifier turns a base name into a safe file-name stem: lowercase, every run
// of non-alphanumeric characters replaced by one underscore, trimmed.
func identifier(base string) string {
	id := nonAlnum.ReplaceAllString(strings.ToLower(base), "_")
	return strings.Trim(id, "_")
}
