// Package generator turns parser JSON IR into a Go acceptance entry point. Each
// generated file embeds the JSON IR and registers it with the acceptance
// runtime. The generator writes thin entry points only; step handlers and the
// runtime are hand-written elsewhere.
//
// This package holds the testable behavior. The command
// (cmd/acceptance-entrypoint-generator) is a thin shell that wires it to the
// process environment.
package generator

import (
	"crypto/sha256"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

// Run is the command adapter: it parses arguments, reads the IR file, resolves
// the recorded feature path, and generates the entry point. It reports usage
// and failures to stderr and returns the process exit code (2 for a usage
// error, 1 for a generation failure, 0 on success). getenv supplies
// environment lookups so the behavior is testable without process state.
func Run(args []string, getenv func(string) string, stderr io.Writer) int {
	if len(args) != 2 {
		fmt.Fprintln(stderr, "usage: acceptance-entrypoint-generator <json-ir> <generated-test-output-dir>")
		return 2
	}
	irPath, outDir := args[0], args[1]

	irBytes, err := os.ReadFile(irPath)
	if err != nil {
		fmt.Fprintf(stderr, "read IR: %v\n", err)
		return 1
	}

	featurePath := getenv("ACCEPTANCE_FEATURE_PATH")
	if featurePath == "" {
		featurePath = irPath
	}

	if err := Generate(irBytes, outDir, featurePath, irPath); err != nil {
		fmt.Fprintf(stderr, "%v\n", err)
		return 1
	}
	return 0
}

// Generate writes the generated entry point and its metadata for one feature
// IR into outDir. featurePath and irPath are recorded in the metadata. An IR
// that is not valid JSON is rejected and nothing is written.
func Generate(irBytes []byte, outDir, featurePath, irPath string) error {
	if !json.Valid(irBytes) {
		return fmt.Errorf("IR %s is not valid JSON", irPath)
	}

	genPath := filepath.Join(outDir, identifier(baseName(irPath))+"_gen.go")
	genContent := generatedSource(string(irBytes))

	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return fmt.Errorf("create output dir: %w", err)
	}
	if err := os.WriteFile(genPath, []byte(genContent), 0o644); err != nil {
		return fmt.Errorf("write generated entry point: %w", err)
	}
	if err := writeMetadata(outDir, featurePath, irPath, genPath, genContent); err != nil {
		return fmt.Errorf("write metadata: %w", err)
	}
	return nil
}

func generatedSource(irJSON string) string {
	var b strings.Builder
	b.WriteString("// Code generated by acceptance-entrypoint-generator. DO NOT EDIT.\n")
	b.WriteString("package main\n\n")
	b.WriteString("import \"estimation/acceptance/runtime\"\n\n")
	b.WriteString("func init() {\n")
	b.WriteString("\truntime.MustRegister(`")
	b.WriteString(irJSON)
	b.WriteString("`)\n")
	b.WriteString("}\n")
	return b.String()
}

func writeMetadata(outDir, featurePath, irPath, genPath, genContent string) error {
	metaDir := filepath.Join(outDir, "metadata")
	if err := os.MkdirAll(metaDir, 0o755); err != nil {
		return err
	}
	sum := sha256.Sum256([]byte(genContent))
	meta := map[string]any{
		"schema_version":      1,
		"feature_path":        featurePath,
		"ir_path":             irPath,
		"implementation_hash": fmt.Sprintf("sha256:%x", sum),
		"hash_scope":          "generated_files",
		"generated_files":     []string{filepath.ToSlash(genPath)},
	}
	data, err := json.MarshalIndent(meta, "", "  ")
	if err != nil {
		return err
	}
	metaPath := filepath.Join(metaDir, metadataName(featurePath))
	return os.WriteFile(metaPath, append(data, '\n'), 0o644)
}

func baseName(path string) string {
	base := filepath.Base(path)
	return strings.TrimSuffix(base, filepath.Ext(base))
}

// nonAlnum matches every run of characters that is not a lowercase letter or
// digit. Both slug builders below collapse such runs to a single separator.
var nonAlnum = regexp.MustCompile(`[^a-z0-9]+`)

// metadataName maps a feature path to its metadata filename: lowercase, every
// run of non-alphanumeric characters replaced by one hyphen, trimmed, with
// ".json" appended.
func metadataName(featurePath string) string {
	slug := nonAlnum.ReplaceAllString(strings.ToLower(featurePath), "-")
	slug = strings.Trim(slug, "-")
	return slug + ".json"
}

// identifier turns a base name into a safe file-name stem: lowercase, every run
// of non-alphanumeric characters replaced by one underscore, trimmed.
func identifier(base string) string {
	id := nonAlnum.ReplaceAllString(strings.ToLower(base), "_")
	return strings.Trim(id, "_")
}

// mutate4go-manifest-begin
// {"version":1,"tested_at":"2026-07-08T22:24:23+05:30","module_hash":"82007761deb053ed2245c37991ae5cce0479d4fe654ba90b9b430da47ec8d34d","functions":[{"id":"func/Run","name":"Run","line":27,"end_line":50,"hash":"551694ce6ff8fb0ef448268cc8e6422fca79cfba2e7534500ce93538bbd249db"},{"id":"func/Generate","name":"Generate","line":55,"end_line":73,"hash":"2ac1c2b9e2e867d51d4d4a3bdcf048ec28960b0d2ac4ac82f714d2ee8ab950a7"},{"id":"func/generatedSource","name":"generatedSource","line":75,"end_line":86,"hash":"e6c204405ec4e04f28718e2bb2abed6114f68ebc9e500393a9c18d35d4cb992b"},{"id":"func/writeMetadata","name":"writeMetadata","line":88,"end_line":108,"hash":"207da8c94ec812074ed22a0cc2cc623aa87f625582f9b4dfd67d1d0e16c05574"},{"id":"func/baseName","name":"baseName","line":110,"end_line":113,"hash":"72668379f4918be41a8a77b8b6d9d239798441bcbd1d445bd6ff06fd5d2943b5"},{"id":"func/metadataName","name":"metadataName","line":122,"end_line":126,"hash":"30808294ba754e48c94160851513e66f075547d9ab7e4be0d1b2039813d74165"},{"id":"func/identifier","name":"identifier","line":130,"end_line":133,"hash":"bca8b15f2899dc4be6b3016745db2ec5390c0adbea3de113270597b99127cc31"}]}
// mutate4go-manifest-end
